use_frameworks!

platform :ios, '12.0'

target 'UIDecoration_Example' do
  pod 'UIDecoration', :path => '../'
  pod 'SnapKit'
  pod 'YYText'

  target 'UIDecoration_Tests' do
    inherit! :search_paths

    
  end
end
